In [1]:
from analysis_funcs import *

In [2]:
jekyll_data_file = './data/jekyll/jekyll_parsed_steps.json'

In [3]:
with open(jekyll_data_file, 'r') as f:
    test_data = json.load(f)

In [4]:
step_definition_strings = stringify_test_cases(test_data, "step_definition")
step_name_strings = stringify_test_cases(test_data, "step_name")
scenario_nums, scenario_title_strings = stringify_test_titles(test_data)

In [5]:
step_name_strings[0]

'1: I have an "index.md" page that contains "{{ site.title }}"\n2: I have a configuration file with "title" set to "Hello World"\n3: I run jekyll build\n4: I should get a zero exit status\n5: the .jekyll-cache directory should exist\n6: the .jekyll-cache/Jekyll/Cache/Jekyll--Cache directory should exist\n7: the _site directory should exist\n8: I should see "<p>Hello World</p>" in "_site/index.html"\n'

In [6]:
ncd_matrix = calculate_pairwise_ncd(step_name_strings)

In [7]:
ncd_matrix

array([[0.        , 0.0673913 , 0.08277405, ..., 0.249501  , 0.49079755,
        0.46      ],
       [0.0673913 , 0.        , 0.11358575, ..., 0.25447316, 0.49390244,
        0.44927536],
       [0.08277405, 0.11358575, 0.        , ..., 0.26122449, 0.48253968,
        0.46567718],
       ...,
       [0.249501  , 0.25447316, 0.26122449, ..., 0.        , 0.54471545,
        0.40472175],
       [0.49079755, 0.49390244, 0.48253968, ..., 0.54471545, 0.        ,
        0.57894737],
       [0.46      , 0.44927536, 0.46567718, ..., 0.40472175, 0.57894737,
        0.        ]])

In [8]:
ncd_matrix.shape

(286, 286)

In [9]:
ncd_matrix[0]

array([0.        , 0.0673913 , 0.08277405, 0.08810573, 0.26464646,
       0.37627119, 0.20484581, 0.37024221, 0.42218543, 0.42218543,
       0.28632479, 0.32575758, 0.41786284, 0.30443975, 0.32319392,
       0.41733547, 0.46974063, 0.4643377 , 0.42692939, 0.32906764,
       0.28849903, 0.24735729, 0.3079922 , 0.39726027, 0.41720779,
       0.42536116, 0.41883117, 0.42696629, 0.30214425, 0.29927007,
       0.29216152, 0.34      , 0.28505747, 0.31055901, 0.31434599,
       0.334     , 0.31210191, 0.49846626, 0.32098765, 0.34722222,
       0.50219619, 0.42332268, 0.43238994, 0.42492013, 0.4328594 ,
       0.40801457, 0.32887701, 0.32569975, 0.25858124, 0.26247289,
       0.26956522, 0.50352609, 0.24832215, 0.25      , 0.24946237,
       0.2196162 , 0.34666667, 0.29453682, 0.29192547, 0.2886836 ,
       0.39236111, 0.29166667, 0.28505747, 0.28375286, 0.28505747,
       0.28505747, 0.28246014, 0.28941176, 0.27610209, 0.30382775,
       0.28915663, 0.24256293, 0.24318182, 0.27934272, 0.26126

In [10]:
cluster1 = np.where(ncd_matrix[0] < 0.2)

In [11]:
cluster1

(array([  0,   1,   2,   3, 246, 247, 266, 281], dtype=int64),)

In [12]:
ncd_matrix[1] # test_num = 2

array([0.0673913 , 0.        , 0.11358575, 0.10964912, 0.26760563,
       0.36317568, 0.20394737, 0.37241379, 0.41749175, 0.41749175,
       0.27234043, 0.3245283 , 0.42289348, 0.29684211, 0.3219697 ,
       0.4208    , 0.47844828, 0.46879536, 0.42389525, 0.33151184,
       0.28349515, 0.25052632, 0.30485437, 0.39761092, 0.40938511,
       0.416     , 0.40938511, 0.4176    , 0.29708738, 0.30024213,
       0.29314421, 0.33695652, 0.29061785, 0.30103093, 0.30252101,
       0.32071713, 0.29809725, 0.49541284, 0.31352459, 0.33399209,
       0.50218978, 0.4156051 , 0.42163009, 0.41719745, 0.42519685,
       0.40471869, 0.33244681, 0.32658228, 0.25968109, 0.26349892,
       0.26839827, 0.50351617, 0.25389755, 0.25321888, 0.25267666,
       0.23566879, 0.34748011, 0.29550827, 0.28865979, 0.28275862,
       0.39273356, 0.29032258, 0.28146453, 0.27790433, 0.28375286,
       0.28146453, 0.28117914, 0.29039813, 0.2817552 , 0.3047619 ,
       0.30215827, 0.25056948, 0.25339367, 0.28738318, 0.26905

In [13]:
cluster2 = np.where(ncd_matrix[1] < 0.15)
cluster2

(array([0, 1, 2, 3], dtype=int64),)

In [14]:
cluster3 = np.where(ncd_matrix[2] < 0.15)
cluster3

(array([0, 1, 2, 3], dtype=int64),)

In [15]:
cluster4 = np.where(ncd_matrix[3] < 0.15)
cluster4

(array([0, 1, 2, 3], dtype=int64),)

In [16]:
ncd_matrix[4]

array([0.26464646, 0.26760563, 0.27272727, 0.2688391 , 0.        ,
       0.28708134, 0.22606925, 0.31544715, 0.3525741 , 0.3525741 ,
       0.2990099 , 0.26902655, 0.38704819, 0.26666667, 0.26642984,
       0.38636364, 0.44186047, 0.43646409, 0.36687307, 0.29452055,
       0.24727273, 0.2372549 , 0.26      , 0.33494364, 0.35834609,
       0.36818182, 0.3568147 , 0.36515152, 0.24363636, 0.33035714,
       0.33187773, 0.30834753, 0.33050847, 0.29615385, 0.29354207,
       0.29050279, 0.2992126 , 0.43686502, 0.29827916, 0.29574861,
       0.49027778, 0.37556561, 0.38187221, 0.37405732, 0.38208955,
       0.38737201, 0.38442822, 0.40232558, 0.30590717, 0.30722892,
       0.31589537, 0.48391421, 0.29958678, 0.27145709, 0.27091633,
       0.25098814, 0.39805825, 0.34279476, 0.28076923, 0.34680851,
       0.36867863, 0.35394456, 0.34110169, 0.33755274, 0.34322034,
       0.34110169, 0.34453782, 0.34632035, 0.34188034, 0.36923077,
       0.35619469, 0.25105485, 0.2557652 , 0.34557235, 0.30353

In [17]:
ncd_matrix[5]

array([0.37627119, 0.36317568, 0.39378238, 0.39078498, 0.28708134,
       0.        , 0.29010239, 0.2056338 , 0.28940217, 0.28940217,
       0.40166667, 0.33636364, 0.33333333, 0.40165289, 0.33890578,
       0.33642384, 0.39588378, 0.39194139, 0.30094467, 0.26951399,
       0.28372093, 0.3322314 , 0.31162791, 0.27793296, 0.27272727,
       0.2781457 , 0.27406417, 0.2807947 , 0.31317829, 0.42357274,
       0.4159132 , 0.29912023, 0.42857143, 0.37235772, 0.39108911,
       0.36550633, 0.39800995, 0.37372449, 0.37055016, 0.35691824,
       0.40736196, 0.28364116, 0.28776042, 0.28496042, 0.29281046,
       0.38179148, 0.49407115, 0.51047619, 0.41476274, 0.42158516,
       0.42736486, 0.41617122, 0.41278066, 0.40604027, 0.40201005,
       0.39101498, 0.50887574, 0.45027125, 0.40487805, 0.47256637,
       0.31497175, 0.45212766, 0.43738977, 0.44112478, 0.44620811,
       0.44444444, 0.43957968, 0.4470377 , 0.43694494, 0.44909091,
       0.47897623, 0.42530756, 0.43006993, 0.46774194, 0.43923

In [19]:
scenario_title_strings[0]

'Default Cache directory'

In [20]:
scenario_ncd_matrix = calculate_pairwise_ncd(scenario_title_strings)

In [21]:
scenario_ncd_matrix.shape

(286, 286)

In [22]:
scenario_ncd_matrix[0]

array([0.        , 0.14754098, 0.37096774, 0.46052632, 0.36666667,
       0.37931034, 0.45945946, 0.41176471, 0.41666667, 0.42253521,
       0.48809524, 0.51041667, 0.50526316, 0.47058824, 0.51546392,
       0.53125   , 0.55339806, 0.56730769, 0.375     , 0.54      ,
       0.61403509, 0.390625  , 0.44230769, 0.38333333, 0.48888889,
       0.50515464, 0.38333333, 0.38095238, 0.4939759 , 0.5257732 ,
       0.46590909, 0.51578947, 0.4691358 , 0.5106383 , 0.53608247,
       0.5       , 0.54639175, 0.51515152, 0.51578947, 0.57407407,
       0.42222222, 0.48888889, 0.50515464, 0.38333333, 0.38095238,
       0.46938776, 0.46938776, 0.37704918, 0.41666667, 0.40277778,
       0.46067416, 0.48192771, 0.39393939, 0.43835616, 0.4109589 ,
       0.42105263, 0.43055556, 0.33802817, 0.42253521, 0.42857143,
       0.48192771, 0.40506329, 0.3974359 , 0.40506329, 0.3974359 ,
       0.3974359 , 0.48453608, 0.46511628, 0.51648352, 0.50526316,
       0.42592593, 0.38333333, 0.4691358 , 0.37704918, 0.38461

In [23]:
scenario_ncd_matrix[4]

array([0.36666667, 0.3559322 , 0.38333333, 0.44594595, 0.        ,
       0.08928571, 0.26388889, 0.34848485, 0.34285714, 0.33333333,
       0.35365854, 0.44680851, 0.44086022, 0.34939759, 0.45263158,
       0.45744681, 0.48514851, 0.49019608, 0.38888889, 0.55102041,
       0.61607143, 0.38709677, 0.42      , 0.36206897, 0.5       ,
       0.50526316, 0.36206897, 0.39344262, 0.34567901, 0.45263158,
       0.38372093, 0.44086022, 0.41772152, 0.41304348, 0.43157895,
       0.40217391, 0.43157895, 0.50515464, 0.4516129 , 0.49056604,
       0.45454545, 0.5       , 0.50526316, 0.36206897, 0.39344262,
       0.44680851, 0.44680851, 0.37288136, 0.44285714, 0.42857143,
       0.49425287, 0.50617284, 0.421875  , 0.43661972, 0.45070423,
       0.43243243, 0.45714286, 0.42028986, 0.44927536, 0.45588235,
       0.49382716, 0.48051948, 0.48684211, 0.48051948, 0.47368421,
       0.48684211, 0.51578947, 0.52380952, 0.49438202, 0.51612903,
       0.40384615, 0.36206897, 0.49367089, 0.37288136, 0.41269

In [24]:
step_names_cosine = calculate_cosine_similarity(step_name_strings)

In [25]:
step_names_cosine[0]

array([1.        , 0.926985  , 0.78242647, 0.85080427, 0.17914505,
       0.14088194, 0.19354167, 0.13306557, 0.07831825, 0.07831825,
       0.18629256, 0.15664575, 0.12744136, 0.18980502, 0.15602743,
       0.12585296, 0.12706318, 0.12526524, 0.07737914, 0.13293238,
       0.14570206, 0.1144095 , 0.16032389, 0.13245433, 0.10845758,
       0.13182369, 0.10780535, 0.10062358, 0.08924276, 0.14234584,
       0.1275527 , 0.20331756, 0.17041549, 0.15688346, 0.19743465,
       0.15479981, 0.16590822, 0.11118908, 0.15977998, 0.1488476 ,
       0.10891055, 0.11074103, 0.13427432, 0.11005502, 0.1026879 ,
       0.08020751, 0.23631972, 0.16229181, 0.16561613, 0.15296678,
       0.1492447 , 0.15392326, 0.14224394, 0.12084992, 0.13041674,
       0.13687944, 0.13592634, 0.11809716, 0.2002769 , 0.1736603 ,
       0.13008667, 0.14051482, 0.15583888, 0.15197004, 0.15126448,
       0.15126448, 0.15582083, 0.11148293, 0.09963535, 0.18013443,
       0.18029684, 0.25927765, 0.24734488, 0.15322228, 0.17751

In [26]:
step_names_cosine[4]

array([0.17914505, 0.1707343 , 0.27150832, 0.22743269, 1.        ,
       0.73609534, 0.54859927, 0.38767754, 0.22521763, 0.22521763,
       0.21992084, 0.16534985, 0.16701827, 0.38710872, 0.17512159,
       0.17703736, 0.14994348, 0.16750838, 0.17442386, 0.16934342,
       0.18561081, 0.26201308, 0.24861984, 0.36034893, 0.17917963,
       0.2138384 , 0.17674968, 0.16725033, 0.12479138, 0.40445765,
       0.33621924, 0.29749671, 0.29029276, 0.31272324, 0.34053024,
       0.33018001, 0.28879597, 0.28002291, 0.17891917, 0.28113324,
       0.08809398, 0.17903345, 0.21275724, 0.17665842, 0.167314  ,
       0.07954023, 0.23251996, 0.13617063, 0.15647306, 0.16669715,
       0.16264098, 0.15603744, 0.12954454, 0.10972592, 0.12062113,
       0.12988317, 0.13087743, 0.12590258, 0.22550864, 0.19416207,
       0.13023705, 0.14308982, 0.15869471, 0.15475496, 0.15403648,
       0.15403648, 0.15867632, 0.12057346, 0.11820226, 0.18463202,
       0.20354723, 0.29979066, 0.28599335, 0.14872528, 0.16670

In [27]:
scenario_titles_cosine = calculate_cosine_similarity(scenario_title_strings)

In [29]:
scenario_titles_cosine[0]

array([1.        , 0.74061257, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.15769315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16502187, 0.        , 0.        ,
       0.        , 0.17873672, 0.16959946, 0.16359297, 0.16359297,
       0.16359297, 0.12420624, 0.14586315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     