In [3]:
from analysis_funcs import *

In [4]:
jekyll_data_file = './data/jekyll/jekyll_parsed_steps.json'

In [5]:
with open(jekyll_data_file, 'r') as f:
    test_data = json.load(f)

In [6]:
step_definition_strings = stringify_test_cases(test_data, "step_definition")
step_name_strings = stringify_test_cases(test_data, "step_name")
scenario_nums, scenario_title_strings = stringify_test_titles(test_data)

In [10]:
step_name_strings[0]

'1: I have an "index.md" page that contains "{{ site.title }}"\n2: I have a configuration file with "title" set to "Hello World"\n3: I run jekyll build\n4: I should get a zero exit status\n5: the .jekyll-cache directory should exist\n6: the .jekyll-cache/Jekyll/Cache/Jekyll--Cache directory should exist\n7: the _site directory should exist\n8: I should see "<p>Hello World</p>" in "_site/index.html"\n'

In [14]:
ncd_matrix = calculate_pairwise_ncd(step_name_strings)

In [15]:
ncd_matrix

array([[0.        , 0.0673913 , 0.08277405, ..., 0.249501  , 0.49079755,
        0.46      ],
       [0.0673913 , 0.        , 0.11358575, ..., 0.25447316, 0.49390244,
        0.44927536],
       [0.08277405, 0.11358575, 0.        , ..., 0.26122449, 0.48253968,
        0.46567718],
       ...,
       [0.249501  , 0.25447316, 0.26122449, ..., 0.        , 0.54471545,
        0.40472175],
       [0.49079755, 0.49390244, 0.48253968, ..., 0.54471545, 0.        ,
        0.57894737],
       [0.46      , 0.44927536, 0.46567718, ..., 0.40472175, 0.57894737,
        0.        ]])

In [16]:
ncd_matrix.shape

(286, 286)

In [24]:
ncd_matrix[0]

array([0.        , 0.0673913 , 0.08277405, 0.08810573, 0.26464646,
       0.37627119, 0.20484581, 0.37024221, 0.42218543, 0.42218543,
       0.28632479, 0.32575758, 0.41786284, 0.30443975, 0.32319392,
       0.41733547, 0.46974063, 0.4643377 , 0.42692939, 0.32906764,
       0.28849903, 0.24735729, 0.3079922 , 0.39726027, 0.41720779,
       0.42536116, 0.41883117, 0.42696629, 0.30214425, 0.29927007,
       0.29216152, 0.34      , 0.28505747, 0.31055901, 0.31434599,
       0.334     , 0.31210191, 0.49846626, 0.32098765, 0.34722222,
       0.50219619, 0.42332268, 0.43238994, 0.42492013, 0.4328594 ,
       0.40801457, 0.32887701, 0.32569975, 0.25858124, 0.26247289,
       0.26956522, 0.50352609, 0.24832215, 0.25      , 0.24946237,
       0.2196162 , 0.34666667, 0.29453682, 0.29192547, 0.2886836 ,
       0.39236111, 0.29166667, 0.28505747, 0.28375286, 0.28505747,
       0.28505747, 0.28246014, 0.28941176, 0.27610209, 0.30382775,
       0.28915663, 0.24256293, 0.24318182, 0.27934272, 0.26126

In [33]:
cluster1 = np.where(ncd_matrix[0] < 0.2)

In [34]:
cluster1

(array([  0,   1,   2,   3, 246, 247, 266, 281], dtype=int64),)

In [29]:
ncd_matrix[1] # test_num = 2

array([0.0673913 , 0.        , 0.11358575, 0.10964912, 0.26760563,
       0.36317568, 0.20394737, 0.37241379, 0.41749175, 0.41749175,
       0.27234043, 0.3245283 , 0.42289348, 0.29684211, 0.3219697 ,
       0.4208    , 0.47844828, 0.46879536, 0.42389525, 0.33151184,
       0.28349515, 0.25052632, 0.30485437, 0.39761092, 0.40938511,
       0.416     , 0.40938511, 0.4176    , 0.29708738, 0.30024213,
       0.29314421, 0.33695652, 0.29061785, 0.30103093, 0.30252101,
       0.32071713, 0.29809725, 0.49541284, 0.31352459, 0.33399209,
       0.50218978, 0.4156051 , 0.42163009, 0.41719745, 0.42519685,
       0.40471869, 0.33244681, 0.32658228, 0.25968109, 0.26349892,
       0.26839827, 0.50351617, 0.25389755, 0.25321888, 0.25267666,
       0.23566879, 0.34748011, 0.29550827, 0.28865979, 0.28275862,
       0.39273356, 0.29032258, 0.28146453, 0.27790433, 0.28375286,
       0.28146453, 0.28117914, 0.29039813, 0.2817552 , 0.3047619 ,
       0.30215827, 0.25056948, 0.25339367, 0.28738318, 0.26905

In [35]:
cluster2 = np.where(ncd_matrix[1] < 0.15)
cluster2

(array([0, 1, 2, 3], dtype=int64),)

In [36]:
cluster3 = np.where(ncd_matrix[2] < 0.15)
cluster3

(array([0, 1, 2, 3], dtype=int64),)

In [37]:
cluster4 = np.where(ncd_matrix[3] < 0.15)
cluster4

(array([0, 1, 2, 3], dtype=int64),)

In [38]:
ncd_matrix[4]

array([0.26464646, 0.26760563, 0.27272727, 0.2688391 , 0.        ,
       0.28708134, 0.22606925, 0.31544715, 0.3525741 , 0.3525741 ,
       0.2990099 , 0.26902655, 0.38704819, 0.26666667, 0.26642984,
       0.38636364, 0.44186047, 0.43646409, 0.36687307, 0.29452055,
       0.24727273, 0.2372549 , 0.26      , 0.33494364, 0.35834609,
       0.36818182, 0.3568147 , 0.36515152, 0.24363636, 0.33035714,
       0.33187773, 0.30834753, 0.33050847, 0.29615385, 0.29354207,
       0.29050279, 0.2992126 , 0.43686502, 0.29827916, 0.29574861,
       0.49027778, 0.37556561, 0.38187221, 0.37405732, 0.38208955,
       0.38737201, 0.38442822, 0.40232558, 0.30590717, 0.30722892,
       0.31589537, 0.48391421, 0.29958678, 0.27145709, 0.27091633,
       0.25098814, 0.39805825, 0.34279476, 0.28076923, 0.34680851,
       0.36867863, 0.35394456, 0.34110169, 0.33755274, 0.34322034,
       0.34110169, 0.34453782, 0.34632035, 0.34188034, 0.36923077,
       0.35619469, 0.25105485, 0.2557652 , 0.34557235, 0.30353